In [206]:
import mysql.connector
import networkx as nx
import scipy as sp
import numpy as np

In [207]:
cnx = mysql.connector.connect(user='root', password='dmkm1234',
                                  host='localhost',
                                  database='dmkm_articles', port='8889')
cursor = cnx.cursor()
G=nx.Graph()

In [208]:
for ii in range(10):
    of = ii*100000
    query = ("select s1.author_id as a_1, s2.author_id as a_2 "
                "from signature s1, signature s2, author_rank r "
                "where s1.author_id != s2.author_id "
                "and s1.article_id = s2.article_id "
                "and s1.author_id = r.author_id "
                "limit 100000 offset "+str(of) )
    cursor.execute(query)
    for (a_1, a_2) in cursor:
        G.add_edges_from([(a_1, a_2)])

In [209]:
A=nx.adjacency_matrix(G)

In [ ]:
for i in range(len(A.nonzero()[0])):
    query = ("select s1.author_id as a_1, s2.author_id as a_2 "
                "from signature s1, signature s2, author_rank r "
                "where s1.author_id != s2.author_id "
                "and s1.article_id = s2.article_id "
                "and s1.author_id = r.author_id "
                "limit 5 offset "+str(of)
                     )
    print( (G.nodes()[A.nonzero()[0][i]],G.nodes()[A.nonzero()[1][i]]) )

In [ ]:
cursor.close()
cnx.close()

In [160]:
#import matplotlib.pyplot as plt

In [161]:
#nx.draw(G)

In [162]:
#plt.show()

In [168]:
print(A)

  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (1, 3)	1
  (1, 4)	1
  (1, 5)	1
  (2, 1)	1
  (3, 1)	1
  (4, 1)	1
  (5, 1)	1


In [165]:
z.toarray()

array([[0, 1, 0, 0, 0, 0]])

In [166]:
print(A.tocsc()[0])

  (0, 1)	1


In [198]:
for i in range(len(A.nonzero()[0])):
    print( (G.nodes()[A.nonzero()[0][i]],G.nodes()[A.nonzero()[1][i]]) )

(2417, 25347)
(25347, 2417)
(25347, 3108)
(25347, 4341)
(25347, 6119)
(25347, 6543)
(3108, 25347)
(4341, 25347)
(6119, 25347)
(6543, 25347)


In [195]:
zip(*A.nonzero())

In [190]:
A.nonzero()

(array([0, 1, 1, 1, 1, 1, 2, 3, 4, 5], dtype=int32),
 array([1, 0, 2, 3, 4, 5, 1, 1, 1, 1], dtype=int32))

In [199]:
G.nodes()

[2417, 25347, 3108, 4341, 6119, 6543]

In [60]:
G.nodes()[0]

110336

In [133]:
print(A.todense())

[[0 1 0 0 0 0]
 [1 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]


In [119]:
np.asarray(nx.nodes(G))

array([ 2417, 25347,  3108,  4341,  6119,  6543])

In [21]:
nx.shortest_path(G,2417,3108)

[2417, 25347, 3108]

In [22]:
A.toarray()

array([[0, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]], dtype=int64)

In [ ]:
flatten = list(set([val for sublist in exit for val in sublist]))
flatten.remove(author)
    except:
        pass
    return flatten
def add_vicinity(graph,author):
    edges = find_neighbour(author)
    G.add_edges_from(edges)
    vicinity = list_author(edges,author)
    return vicinity
def graph_r(G,author,k):
    if k >= 1:
        vici = add_vicinity(G,author)
        for authors in vici:
            k = k - 1
            graph_r(G,authors,k)

In [55]:
cnx = mysql.connector.connect(user='root', password='dmkm1234',
                                  host='localhost',
                                  database='dmkm_articles', port='8889')
cursor = cnx.cursor(buffered=True)
cursorb = cnx.cursor(buffered=True)

query = ("select a_1, a_2 from graph where distance is null limit 10")
cursor.execute(query)

query2 = ("update graph "
          "set distance = %s "
          "where a_1= %s and a_2= %s and distance is null "
                )
i=0
for (a_1,a_2) in cursor:
    G=nx.Graph()
    k=5
    graph_r(G,a_1,k)
    graph_r(G,a_2,k)
    i = i+1
    d = None
    try:
        d = str(len(nx.shortest_path(G,a_1,a_2))-1)
        cursorb.execute(query2,(d,a_1,a_2))
        cnx.commit()
        print(str(a_1)+' '+str(a_2)+' '+str(d)+' conn')
    except:
        pass
cursorb.close()
cursor.close()
cnx.close()

4 377789 1 conn
4 434880 1 conn
4 441970 1 conn
4 447077 1 conn
4 450410 1 conn
5 36550 1 conn
5 48482 1 conn
5 60209 1 conn
5 75498 1 conn
5 143215 1 conn


In [344]:
#d=0
#query2 = ("update graph "
#                  "set distance = "+str(d)+" "
#                  "where a_1="+str(a_1)+" and a_2="+str(a_2)+" and distance is null ")
#print(query2)

update graph set distance = 0 where a_1=2 and a_2=155241 and distance is null 


In [50]:
#a1=2
#a2=62182
#k=5
#G=nx.Graph()
#graph_r(G,a1,k)
#graph_r(G,a2,k)

In [51]:
#len(G.nodes())

167

In [52]:
#len(nx.shortest_path(G,a1,a2))-1

1

In [353]:
#for author in cursor:
#    pass
#cursor1
#cnx.commit()
#cursor.close()
#cnx.close()

In [235]:
#G.edges()

In [236]:
#nx.clustering(G)